### ISSUE TITLE
Trajectories keep violating constraints

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr_interface#133]
This messes the wait=True param in the RobotCommander.

The main suspect is the fact that J1 and J2 are not independently controlled.

**Comment by beatrizleon** [comment]
I haven't been able to find a problem with the code but these are the things I noticed:

Planning trajectories for the arm:

The trajectories will execute correctly as long as:
1) the ground is loaded so the planner takes it into account and 
2) the start state of the planning interface is set to "current". This is really annoying as that should be set by default by moveit after executing a previous traj, but instead if the update button is not clicked after executing a previous trajectory, the start state will still be the one for the previous trajectory. This makes moveit to send a planned trajectory that do not reflect where the robot is now and therefore a PATH Tolerance is violated.

Planning trajectories for the hand:

The trajectories executed for the hand mainly fail at the end with goal velocity tolerance because the desired velocity is zero but the current one is no. I checked and the hand is not stable in gazebo and therefore some of the joints have velocities even when the hand is not moving.

This can be solved increasing the param:
stopped_velocity_tolerance
but I have seen velocity values for some joints of about 45. Also needs to be changed for the arm as the hand wrist joints are defined there

Sometimes when planning for a random position of the hand, it fails due to a goal tolerance of Position Error of about 0.5, then we could increase the Position Tolerance: 0.4 to 0.6 for the hand joints.

Submitted the issue here: ros-planning/moveit_ros#646

Reported issue with velocities here:
#140

**Comment by guihomework** [comment]
I think this issues is not only due to the velocity being violated but also from the j1/j2 as @toliver said. We could reproduce that here.
j1/j2 executed movements do not match the requested command due to the single j0 command in the background and weird distribution of the force to the two joints which makes them not move in a coupling mode. In the current state one could command j1 to 90 and j2 to 0 and this would never be reached on any hand, real or simulation, and would always fail with goal tolerances. 90 degrees of goal tolerance is not acceptable obviously.

We discussed that force distribution and coupling in simulation in the past and never found a good solution. How does gazebo handle mimic now ?
But even if simulation was okay, that problem would still be present on the real hand with variable coupling.

It seems the solution would be to have j0 considered in the tolerance check. However such a solution requires a specific trajectory controller. 

You still have a pending pull request https://github.com/ros-controls/ros_controllers/pull/185 on the trajectory controller for partial trajectory, maybe it would be worth issuing your own trajectory controller as part of sr_mechanism_controllers, that does both partial trajectory and cleaner tolerance check on j0 (or on j1+j2) ?

**Comment by toliver** [comment]
I think that for the moment our best fix for this is to set trajectory and goal tolerances of 90 degrees for J1 and J2 (as they can be specified per-joint).

This might seem weird if you are moving the hand in free space, but if you are holding an object, the goal could be unreachable (maybe you send a target that is actually inside the object to get a firm grip). In this particular case I don't think that we want the goal to fail due to a goal violation. We want it to succeed to indicate when the trajectory execution has effectively ended.

**Comment by guihomework** [comment]
How did the pr2 gripper work with that "cannot reach inside the object" ? 
Maybe it had not trajectory controller ?

IMHO one clean way would be to set a per joint tolerance larger when there is a grasp involved, but handle correctly the j0 when the hand moves in freespace (which happens in pre-grasp / reach for instance). It is not good to have position goal violated in freespace.

I also think the cleanest way would be to do reactive grasping. Close until contact (maybe with a goal violated then) and then switch the hand controller doing a position + force control. I know this is another level of grasping, and we are not ready for that on our side either (but planning to do that in the future).
